In [2]:
import torch
import numpy as np
import sys

In [3]:
torch.__version__

'1.8.0'

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device("cuda:0" if (torch.cuda.is_available()) else "cpu")
device

device(type='cuda', index=0)

In [6]:
# như tất cả các bạn đều biết, mọi thứ có thể tăng tốc nếu bạn có GPU NVIDIA
#CUDA là khung mà NVIDIA phát triển, cho phép chúng tôi sử dụng GPU để tính toán

# PC của tôi là MAC và tôi không có CUDA


In [7]:
X_train = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
Y_train = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [8]:
#please tạo tensors từ mảng numpy này
# torch.from_numpy (bản sao) hoặc torch.tensor (không phải bản sao!)
inputs  = torch.tensor(X_train)
targets = torch.tensor(Y_train)

#please in hình dạng của những cái căng này
# sử dụng .size () hoặc .shape
inputs.shape, targets.shape

(torch.Size([15, 3]), torch.Size([15, 2]))

In [9]:
from torch.utils.data import TensorDataset

In [10]:
# đặt tập dữ liệu này lên đầu các đầu vào và mục tiêu của chúng tôi
#format: TensorDataset (X, y) trong đó X.shape là (m, n) và y.shape là (m, k)
ds = TensorDataset(inputs, targets)

In [11]:
ds [1] # đây là một bộ của hai tenxơ, x và y tương ứng
# đây LÀ ĐỊNH DẠNG mà pyTorch muốn !!!

(tensor([91., 88., 64.]), tensor([ 81., 101.]))

In [12]:
#this dataloader sẽ tự động tạo một điều tra viên, hãy xem từng lô
#means, bạn có thể chỉ cần thực hiện một vòng lặp for trên bộ dữ liệu này
# nếu bạn KHÔNG MUỐN sử dụng DataLoader này, vẫn ổn! Nhưng bạn có
#để chọn thủ công lô nhỏ (giống như chúng tôi làm trong lớp lô nhỏ LR của mình)
from torch.utils.data import DataLoader #this guy is randomized (nếu bạn đặt Shuffle = true)

batch_size = 3 # đây là bất kỳ số nào bạn thích
# too small thì mã của bạn chạy chậm
# too to thì bạn có thể gặp lỗi "hết bộ nhớ"

dl = DataLoader (ds, batch_size, shuffle = True)

In [13]:
import torch.nn as nn 
#stands cho mạng nơ-ron; mô-đun chứa nhiều lớp có thể
# xác định mạng nơ-ron của chúng tôi
# chỉ sử dụng một lớp ....
# chúng tôi sẽ quay lại đây và thêm một lớp nữa ....
#format: nn.Linear (in_features, out_features)
#format: nn.Linear (nhiệt độ; lượng mưa; hum, cam; táo)

# model = nn.Linear (3, 2)

#linear về cơ bản là phép nhân ma trận đơn giản ....
# Nhiều tên khác: Ở Keras, chúng tôi gọi là Dense. Trong TensorFlow, chúng tôi đã gọi là FullConnected

#Keras rất cao cấp - không tốt cho nghiên cứu / phát triển (chủ yếu cho giáo dục ...)
#TensorFlow do Google phát triển - nó khá tốt

# cho mô hình rất lớn, phức tạp, hiệu suất cao - TensorFlow tốt hơn / được tối ưu hóa nhiều
     # chúng ở cấp thấp hơn PyTorch
# đối với hầu hết mọi mô hình mà chúng tôi sử dụng (ngay cả trong nghiên cứu) - PyTorch tốt hơn nhiều
# do đồ thị tính toán của nó .....

#TensorFlow hỗ trợ một thứ gọi là TensorFlowLite, đó là cách
# bạn muốn sử dụng cho điện thoại di động ....

In [14]:
#I wonder whether have one extra layer, can reduce the loss!
# model = nn.Sequential(
#     nn.Linear(3, 10),
#     nn.Linear(10, 2)
# )  #this is fine, but this is not the best practice!!
   #because in the future, there are many layers and complex stuffs in neural network....

In [15]:
#class là phương pháp hoàn hảo và tốt nhất để tạo mạng nơ-ron thuộc bất kỳ loại nào ...

#format:
'''
class AnyNameCapitalized(nn.Module): #it must inherit nn.Module
    def __init__():
        super().__init__()  #super is basically inheriting nn.Module init
        #we define all the layers here.....
        
    def forward(self, x):   #YOU CANNOT CHANGE THIS NAME, it MUST BE "forward"
        x = layer1()
        x = layer2()
        return x
'''

class NeuralNetwork(nn.Module):
    
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [16]:
model = NeuralNetwork(  3  ,  10   ,  2 )

In [17]:
#model.weight
#model.fc1.weight
#model.fc2.weight
# model.fc1.weight #by default, these weights are uniformly close to 0

In [18]:
# model.weight.shape  #this one is basically in the shape (out_features, in_feature)

#you can imagine X @ W^T
#after you transpose W, W^T becomes [3, 2]
#which now you can do X @ W^T which is (anything, 3) @ (3, 2)

In [19]:
# model.bias  #why two bias???
# model.fc1.bias

In [20]:
# list(model.parameters())  #this will list all the parameters (it's a object)

In [21]:
#p.numel() just flatten everything....
sum(p.numel() for p in model.parameters() if p.requires_grad)

#why 8 here??? - 6 weights and 2 bias.....

62

In [22]:
#so how do we use our model
model

NeuralNetwork(
  (fc1): Linear(in_features=3, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=2, bias=True)
  (relu): ReLU()
)

In [23]:
#so you can perform a forward pass, simply using 
#format: model(inputs)

# print("Inputs: ", inputs.shape)

# output = model(inputs)  #(15, 3) @ (3, 2) = (15, 2)
# print(output.shape)  #why output.shape is 15, 2??

In [24]:
#under the nn module, there are many loss function
J_fn = nn.MSELoss()

#later on, you will know how to use this.....

In [31]:
optim = torch.optim.SGD(model.parameters(), lr=0.0001)

In [25]:
# num_epochs = 5  #it depends....trial and error....
# #for num_epochs
# for epoch in range(num_epochs):
#     #for dataloader
#     for x, y in dl:  
#         #x: (batch, features) = (3, 3) 
#         #y: (batch, target)   = (3, 2)
        
#         #optional: you can put your x and y inside the CUDA (GPU) for speed up
#         x.to(device)  #device is either cpu or cuda
#         y.to(device)

#         #1. predict (forward pass)
#         yhat = model(x)
        
#         #2. calculate loss
#         #sklearn.metrics.mse(y, yhat)
#         #format: J_fn(inputs, targets)
#         loss = J_fn(yhat, y)
        
#         #3. calculate gradient
#         #3.1 clear out the previous gradients
#         #format: optimizer.zero_grad()
#         optim.zero_grad()
        
#         #3.2 called backward() on loss to retrieve all the gradients (backpropagation/backward pass)
#         loss.backward()  #why called backward on loss!?
#         #backward DOES NOT adjust the weight YET....just backpropagation
#         #we want to calculate the gradients of all parameters (8 - 6 weights and 2 bias)
#         #IN RESPECT TO THE LOSS....dJ/dw11,  dJ/dw12, dJ/dw13....., dJ/db1, dJ/db2
        
#         #4. update the parameters using the optim
#         #W = W - alpha * gradient  #we don't need to do this here.....
#         optim.step()  #optim already has learning rate, it also know all the parameters

In [33]:
num_epochs = 10 
for epoch in range(num_epochs):
    for x, y in dl:  
        x.to(device)  #device is either cpu or cuda
        y.to(device)

        yhat = model(x)
        loss = J_fn(yhat, y)
        optim.zero_grad()
        loss.backward()  
        optim.step()  
        
        print(f"Epoch: {epoch} - Loss: {loss}")
        
        #can you guys help tell what is the best hidden size?
        #final exam is on Nov 22 9 - 12
            #signal processing
            #deep learning - pytorch
        #project will be decided by Mr. Akraradet
        #8 classes......14 lectures....
        

Epoch: 0 - Loss: 8590.18359375
Epoch: 0 - Loss: 4780.64990234375
Epoch: 0 - Loss: 6161.79052734375
Epoch: 0 - Loss: 7275.24072265625
Epoch: 0 - Loss: 10736.9033203125
Epoch: 1 - Loss: 6945.66357421875
Epoch: 1 - Loss: 11005.8583984375
Epoch: 1 - Loss: 4419.08544921875
Epoch: 1 - Loss: 13357.8876953125
Epoch: 1 - Loss: 5743.67138671875
Epoch: 2 - Loss: 4717.71728515625
Epoch: 2 - Loss: 6766.87548828125
Epoch: 2 - Loss: 6918.33154296875
Epoch: 2 - Loss: 10840.4140625
Epoch: 2 - Loss: 12169.3310546875
Epoch: 3 - Loss: 10718.0458984375
Epoch: 3 - Loss: 8208.2412109375
Epoch: 3 - Loss: 4403.826171875
Epoch: 3 - Loss: 9689.513671875
Epoch: 3 - Loss: 8357.4951171875
Epoch: 4 - Loss: 7179.408203125
Epoch: 4 - Loss: 6906.91552734375
Epoch: 4 - Loss: 12154.45703125
Epoch: 4 - Loss: 6750.36669921875
Epoch: 4 - Loss: 8350.578125
Epoch: 5 - Loss: 9679.0068359375
Epoch: 5 - Loss: 8347.7685546875
Epoch: 5 - Loss: 7170.267578125
Epoch: 5 - Loss: 7919.97509765625
Epoch: 5 - Loss: 8189.26708984375
Epoch

In [34]:

ds[0:2]

(tensor([[73., 67., 43.],
         [91., 88., 64.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.]]))

In [35]:
#please create two numpy array of 
# [74, 68, 42], [92, 88, 65]
x = np.array([[74, 68, 42], [92, 88, 65]], dtype='float32')
#float  means 32 bits
#double means 64 bits

#please make it a tensor
x_tensor = torch.tensor(x)

#then use our model to predict the number of oranges and apples
yhat = model(x_tensor)
yhat

#print the loss comparing with ds[0] and ds[1] - look at the y part ok...
ytest = ds[0:2][1]
loss = J_fn(yhat, ytest)
print(loss)

tensor(6109.3696, grad_fn=<MseLossBackward>)
